# -*- coding: utf-8 -*-
"""lab_scraper.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ve1wZspfhdMnGo96ExE3XKDV2Jmotd8E
"""

import requests
from bs4 import BeautifulSoup
import pandas as pd

def lab_scraper(url):
    # Send a GET request to the URL
    response = requests.get(url)
    soup = BeautifulSoup(response.content, 'html.parser')

    lab_name =
    mrp =
    discounted_price =
    tests_included =
    address =
    return lab_name, mrp, discounted_price, tests_included, address

# Example usage
data = []
urls = ['https://www.labuncle.com/packages/good-health-package-1433',
        'https://www.labuncle.com/packages/health-champion-radiology-package-1677'
       ]

for url in urls:
    data.append(lab_scraper(url))

df = pd.DataFrame(data, columns=['Lab Name', 'MRP', 'Discounted Price', 'Tests Included', 'Address'])

df.to_csv('labs_data.csv', index=False)