# -*- coding: utf-8 -*-
"""pincode_scraper.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BAvdbROtM3VRYNuc57xcpUOfGj48PZpX
"""

from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
import time

def scrape_medicine_availability(pincode, url):
    driver = webdriver.Chrome()

    driver.get(url)

    pincode_field = driver.find_element(By.ID, 'pincode-input')
    pincode_field.clear()
    pincode_field.send_keys(pincode)
    pincode_field.send_keys(Keys.RETURN)


    time.sleep(5)

    delivery_date = driver.find_element(By.ID, 'delivery-date-element')
    delivery_date_text = delivery_date.text

    driver.quit()

    return delivery_date_text, pincode, url

pincode = '110001'  # Example pincode
url = 'https://www.tata1mg.com/...'  # Example URL
print(scrape_medicine_availability(pincode, url))