# -*- coding: utf-8 -*-
"""scraper.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dK7EbABnMsAgRdA9HO82hrgEZpjQn5p7
"""

import requests
from bs4 import BeautifulSoup
import pandas as pd

def scrape_pharmeasy_data(url):
    #Send a GET request to the URL
    response = requests.get(url)
    soup = BeautifulSoup(response.content, 'html.parser')
    name =
    mrp =
    discounted_price =
    marketer =
    salts =
    return name, mrp, discounted_price, marketer, salts, url

def scrape_netmeds_data(url):
    response = requests.get(url)
    soup = BeautifulSoup(response.content, 'html.parser')
    name =
    mrp =
    discounted_price =
    marketer =
    salts =
    return name, mrp, discounted_price, marketer, salts, url

data = []
urls = ['list of your URLs here']
for url in urls:
    if 'pharmeasy' in url:
        data.append(scrape_pharmeasy_data(url))
    elif 'netmeds' in url:
        data.append(scrape_netmeds_data(url))

df = pd.DataFrame(data, columns=['Name', 'MRP', 'Discounted Price', 'Marketer', 'Salts', 'URL'])

df.to_csv('medicines.csv', index=False)



